### ISSUE TITLE
Pb de date

### ISSUE THREAD

**Issue by dytq** [Sholde/ProjetBD#23]
Il faut récupérer la date du jour et la mettre à jour dans les requêtes

**Comment by Sholde** [comment]
cad ?

**Comment by dytq** [comment]
Non mais si on le temps (mdr) il faudra mettre à jour le site quand la date de projection d'un film est obselte mais ca n'a rien n'avoir avec les requêtes pour le coup 
Le problèmes si on suppr un se_joue_dans ca fausse nos informations dans la partie admin (pour obtenir le profit de chaque cinéma)

**Comment by Sholde** [comment]
nan mais il faut juste comparer la date du jour et celle de la projection ya rien a faire

**Comment by Sholde** [comment]
Dans la requete faut juste dire si la date de la projection est apres la date daujourdhui cest tout
