### ISSUE TITLE
On est un peu perdu sur le site :/

### ISSUE THREAD

**Issue by dytq** [Sholde/ProjetBD#37]
il faut faire en sorte de mieux se retrouver dans le site en ajoutant des liens

**Comment by Sholde** [comment]
Fait la meme chose que tas fait pour la page dacceuil pour les autres pages

**Comment by dytq** [comment]
ok 
Dans mes commits ce n'est pas encore implémenté

**Comment by dytq** [comment]
En fait c'est complique j'ai mal implémente mon css car si j'utilise requiere la feuille de style entre en conflit

**Comment by dytq** [comment]
j'ai ajouter plus de liens bon j'ai la flemme de tout re tout changer
